name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Build with official Buildozer Docker image
      uses: docker://kivy/buildozer:latest
      env:
        BUILDER_ALLOW_ROOT: "1"
      with:
        args: android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
